name = "LightPropagationAI"
uuid = "e45ca9be-56a6-4e23-a967-296dca30f0df"
authors = ["heltonmc <heltonmc@protonmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
